/**
 * P6-FIX-012 (Issue #145): the server-side final Runtime Authorization gate.
 *
 * This is the ONLY place that turns a verified Approval Chain Linkage and a
 * runtime-eligible Human Decision into an `authorized_not_executed` receipt, and
 * only after an exact-binding atomic ApprovalStore claim wins.
 *
 * TEMPORAL FRESHNESS (P6-FIX-012 repair). The authoritative authorization
 * instant is generated by an injectable trusted clock AFTER the final
 * asynchronous evidence read — never before the resolver wait. That single fresh
 * timestamp drives executor-session validation, Linkage verification, Human
 * Decision eligibility, expiry derivation, and the final CAS, so a slow resolver
 * cannot let a stale timestamp survive across the async boundary. The client
 * never supplies the time.
 *
 * Ordering: early route guards → async evidence resolution → snapshot the bundle
 * once → fresh final timestamp → snapshot the session once → derive the current
 * executor → verify all evidence at the fresh timestamp → final RBAC recheck →
 * final kill-switch recheck → immediate exact-binding CAS with the same fresh
 * timestamp → construct receipt. The consuming path and the non-consuming
 * dry-run path share this exact core so they classify identical evidence the
 * same way before any claim.
 *
 * It never calls a provider, never creates an ExecutionResult, never returns an
 * externalRef, and never promotes a WorkUnit. It imports the single server-
 * private receipt constructor and no provider client.
 */

import type { Session } from "./session.ts"
import type { ApprovalStore } from "./approvalStore.ts"
import type { ApprovalActionType } from "../domain/types.ts"
import type { TenantId } from "../tenant/types.ts"
import { hasPermission } from "./rbac.ts"
import { areExternalActionsEnabled } from "./externalActions.ts"
import { createCanonicalSessionIdentity } from "../phase6/canonicalIdentity/index.ts"
import {
  evaluateRuntimeAuthorizationEligibility,
  projectRuntimeAuthorizationAudit,
  noopRuntimeAuthorizationAuditSink,
  snapshotDeepFrozen,
  type RuntimeAuthorizationAuditSink,
  type RuntimeAuthorizationAuditEvent,
  type RuntimeAuthorizationEligibleEvidence,
  type RuntimeAuthorizationResult,
  type RuntimeAuthorizationEligibilityState,
} from "../phase6/runtimeAuthorization/index.ts"
import { constructRuntimeAuthorizationReceipt } from "./runtimeAuthorizationReceipt.ts"
import type {
  RuntimeAuthorizationEvidenceResolver,
  RuntimeAuthorizationEvidenceBundle,
} from "./runtimeAuthorizationEvidenceResolver.ts"

const EXECUTE_PERMISSION = "workunit.execute_external_action" as const

/** Injectable trusted clock. The client never supplies the time. */
export type RuntimeAuthorizationClock = {
  now(): string
}

/** Production clock: the server wall clock as a pinned UTC ISO string. */
export const systemRuntimeAuthorizationClock: RuntimeAuthorizationClock = {
  now() {
    return new Date().toISOString()
  },
}

// Test-only clock seam so route-level tests (which cannot inject a clock into
// the route) can pin the post-resolution evaluation instant to fixture times.
// Never set in production; an explicit per-call clock always takes precedence.
let testClockOverride: RuntimeAuthorizationClock | null = null

export function setRuntimeAuthorizationClockForTests(clock: RuntimeAuthorizationClock | null): void {
  testClockOverride = clock
}

export function resetRuntimeAuthorizationClockForTests(): void {
  testClockOverride = null
}

function resolveClock(explicit?: RuntimeAuthorizationClock): RuntimeAuthorizationClock {
  return explicit ?? testClockOverride ?? systemRuntimeAuthorizationClock
}

export type AuthorizeRuntimeCommandInput = {
  readonly session: Session
  readonly request: {
    readonly tenantId: string
    readonly workUnitId: string
    readonly actionPreviewId: string
    readonly approvalId: string
    readonly actionType: string
  }
  readonly approvalStore: ApprovalStore
  readonly evidenceResolver: RuntimeAuthorizationEvidenceResolver
  readonly env?: NodeJS.ProcessEnv
  readonly clock?: RuntimeAuthorizationClock
  readonly auditSink?: RuntimeAuthorizationAuditSink
}

type EligState = Exclude<RuntimeAuthorizationEligibilityState, "eligible">

function fail(state: EligState, issueCode: string): RuntimeAuthorizationResult {
  return Object.freeze({ ok: false, state, issue_code: issueCode })
}

/** Never let a malformed session throw during the RBAC check. */
function hasExecutePermission(session: Session): boolean {
  try {
    return hasPermission(session, EXECUTE_PERMISSION)
  } catch {
    return false
  }
}

function isNonEmptyString(value: unknown): value is string {
  return typeof value === "string" && value.length > 0
}

/**
 * Single-read snapshot of the current session. After evidence resolution the
 * session is snapshotted ONCE; canonical executor construction, session expiry,
 * final tenant identity, and final RBAC all read this one snapshot, never a
 * later read of the original session object.
 */
type SessionSnapshot = {
  readonly userId: unknown
  readonly tenantId: unknown
  readonly role: unknown
  readonly email: unknown
  readonly isDevSession: unknown
  readonly sessionId: unknown
  readonly createdAt: unknown
  readonly expiresAt: unknown
  readonly service_account?: unknown
  readonly on_behalf_of?: unknown
}

function snapshotSession(session: unknown): SessionSnapshot | null {
  if (typeof session !== "object" || session === null || Array.isArray(session)) return null
  const s = session as Record<string, unknown>
  const snap: Record<string, unknown> = {}
  for (const key of Object.keys(s)) snap[key] = s[key]
  return snap as unknown as SessionSnapshot
}

/**
 * Build the linkage verification context from the RAW server-owned sources,
 * stamping the fresh authorization instant into both `evaluated_at` and the
 * nested Identity Independence input's `evaluated_at` (one evaluation instant).
 */
function buildVerificationContext(
  sources: RuntimeAuthorizationEvidenceBundle["sources"],
  now: string,
): Record<string, unknown> {
  const rawIdentity = sources.identity_input
  const identityInput =
    rawIdentity !== null && typeof rawIdentity === "object" && !Array.isArray(rawIdentity)
      ? { ...(rawIdentity as Record<string, unknown>), evaluated_at: now }
      : rawIdentity
  return {
    tenant_id: sources.tenant_id,
    human_decision: sources.human_decision,
    review_evidence: sources.review_evidence,
    identity_input: identityInput,
    action_preview: sources.action_preview,
    approval_record: sources.approval_record,
    evaluated_at: now,
    revoked_review_evidence_ids: sources.revoked_review_evidence_ids,
    consumed_review_evidence_ids: sources.consumed_review_evidence_ids,
    revoked_approval_ids: sources.revoked_approval_ids,
    consumed_approval_ids: sources.consumed_approval_ids,
    revoked_approval_linkage_ids: sources.revoked_approval_linkage_ids,
    consumed_approval_linkage_ids: sources.consumed_approval_linkage_ids,
  }
}

// ─── Resolution + synchronous finalization ──────────────────────

type CoreOk = { readonly ok: true; readonly evidence: RuntimeAuthorizationEligibleEvidence; readonly sessionSnap: SessionSnapshot }
type CoreErr = { readonly ok: false; readonly state: EligState; readonly issueCode: string }
type CoreResult = CoreOk | CoreErr

export type RuntimeAuthorizationCoreInput = {
  readonly session: Session
  readonly request: AuthorizeRuntimeCommandInput["request"]
  readonly evidenceResolver: RuntimeAuthorizationEvidenceResolver
  readonly env?: NodeJS.ProcessEnv
  readonly clock?: RuntimeAuthorizationClock
}

/** The inert inert-identifier request shape both consuming functions accept. */
type RuntimeAuthorizationRequest = AuthorizeRuntimeCommandInput["request"]

function requestFieldsValid(request: RuntimeAuthorizationRequest): boolean {
  return (
    isNonEmptyString(request.tenantId) &&
    isNonEmptyString(request.workUnitId) &&
    isNonEmptyString(request.actionPreviewId) &&
    isNonEmptyString(request.approvalId) &&
    isNonEmptyString(request.actionType)
  )
}

/**
 * The SYNCHRONOUS finalization step shared by the consuming gate and the dry-run
 * evaluator. Given the already-resolved (snapshotted) bundle, the session
 * snapshot, the fresh post-resolution `claimAt` instant, and the inert request,
 * it re-derives the current executor and runs `evaluateRuntimeAuthorizationEligibility`
 * (Linkage verification, Human Decision matrix, executor-vs-approver, bounded
 * expiry). It performs NO `await`, NO RBAC/kill-switch policy check, and NO audit
 * emission — the consuming function owns those and keeps them claim-adjacent.
 * Returns the eligible evidence bound to `claimAt`.
 */
function evaluateResolvedRuntimeAuthorization(input: {
  readonly bundleSnap: RuntimeAuthorizationEvidenceBundle
  readonly sessionSnap: SessionSnapshot
  readonly claimAt: string
  readonly request: RuntimeAuthorizationRequest
}): CoreResult {
  const { bundleSnap, sessionSnap, claimAt, request } = input

  const envelope = bundleSnap.intendedAction
  if (
    !isNonEmptyString(envelope?.tenantId) || envelope.tenantId !== request.tenantId ||
    !isNonEmptyString(envelope.workUnitId) || envelope.workUnitId !== request.workUnitId ||
    !isNonEmptyString(envelope.actionPreviewId) || envelope.actionPreviewId !== request.actionPreviewId ||
    !isNonEmptyString(envelope.approvalId) || envelope.approvalId !== request.approvalId ||
    !isNonEmptyString(envelope.actionType) || envelope.actionType !== request.actionType ||
    !isNonEmptyString(envelope.targetHash) ||
    !isNonEmptyString(envelope.payloadHash)
  ) {
    return { ok: false, state: "stale", issueCode: "runtime_authorization_state_missing" }
  }

  // Current executor identity, derived at the fresh instant from the session
  // snapshot only. Sync; no clock read here (claimAt is supplied).
  const executorResult = createCanonicalSessionIdentity(sessionSnap, {
    actor_kind: "executor",
    expected_tenant_id: request.tenantId,
    observed_at: claimAt,
  })
  if (!executorResult.ok) {
    return { ok: false, state: "forbidden", issueCode: "runtime_authorization_executor_invalid" }
  }
  const executor = executorResult.identity
  const sessionExpiresAt = sessionSnap.expiresAt

  const context = buildVerificationContext(bundleSnap.sources, claimAt)
  const eligibility = evaluateRuntimeAuthorizationEligibility({
    linkage: bundleSnap.linkage,
    linkage_context: context,
    executor_identity: executor,
    intended_action: {
      tenant_id: envelope.tenantId,
      workunit_id: envelope.workUnitId,
      action_preview_id: envelope.actionPreviewId,
      approval_id: envelope.approvalId,
      action_type: envelope.actionType,
      target_hash: envelope.targetHash,
      payload_hash: envelope.payloadHash,
    },
    session_expires_at: typeof sessionExpiresAt === "string" ? sessionExpiresAt : "",
    issued_at: claimAt,
  })
  if (!eligibility.ok) {
    return { ok: false, state: eligibility.state, issueCode: eligibility.issue_codes[0] ?? "runtime_authorization_state_missing" }
  }
  return { ok: true, evidence: eligibility.evidence, sessionSnap }
}

/**
 * Resolve + snapshot the bundle. This is the ONLY asynchronous step; everything
 * after it in the consuming functions is synchronous through claim initiation.
 * Returns the snapshotted bundle, or null when evidence is unavailable.
 */
async function resolveBundleSnapshot(
  resolver: RuntimeAuthorizationEvidenceResolver,
  request: RuntimeAuthorizationRequest,
): Promise<RuntimeAuthorizationEvidenceBundle | null> {
  const bundle = await resolver.resolveEvidenceBundle({
    tenantId: request.tenantId,
    workUnitId: request.workUnitId,
    actionPreviewId: request.actionPreviewId,
    approvalId: request.approvalId,
  })
  if (bundle === null) return null
  const snap = snapshotDeepFrozen(bundle) as RuntimeAuthorizationEvidenceBundle | null
  if (snap === null || typeof snap !== "object") return null
  return snap
}

function auditFrom(
  kind: Parameters<typeof projectRuntimeAuthorizationAudit>[0]["event_kind"],
  evidenceOrRequest: RuntimeAuthorizationEligibleEvidence | AuthorizeRuntimeCommandInput["request"],
  state: RuntimeAuthorizationEligibilityState | "authorized_not_executed",
  now: string,
  issueCodes: readonly string[] = [],
) {
  const src = evidenceOrRequest as Record<string, unknown>
  return projectRuntimeAuthorizationAudit({
    event_kind: kind,
    tenant_id: src.tenant_id ?? src.tenantId,
    workunit_id: src.workunit_id ?? src.workUnitId,
    action_preview_id: src.action_preview_id ?? src.actionPreviewId,
    approval_id: src.approval_id ?? src.approvalId,
    action_type: src.action_type ?? src.actionType,
    state,
    issue_codes: issueCodes,
    evaluated_at: now,
  })
}

// ─── Consuming gate ─────────────────────────────────────────────

/**
 * The final runtime authorization gate. Returns a frozen discriminated result
 * with a stable internal issue code. On success the receipt is
 * `authorized_not_executed`; no provider is called and no state beyond the
 * one-time-use Approval claim is mutated. The full audit lifecycle
 * (requested → eligible → claimed → created, or rejected/replayed/blocked) is
 * emitted to the supplied sink.
 */
export async function authorizeRuntimeCommand(
  input: AuthorizeRuntimeCommandInput,
): Promise<RuntimeAuthorizationResult> {
  const clock = resolveClock(input.clock)
  const env = input.env ?? process.env
  const sink = input.auditSink ?? noopRuntimeAuthorizationAuditSink

  // Audit events are BUFFERED here and flushed to the externally-supplied sink
  // ONCE, after the terminal result. The sink is never invoked inside the
  // security-critical window (between the final RBAC/kill-switch checks and the
  // claim), so a hostile sink cannot flip policy state after the last check.
  const events: RuntimeAuthorizationAuditEvent[] = []
  const flushAndReturn = async (result: RuntimeAuthorizationResult): Promise<RuntimeAuthorizationResult> => {
    try {
      await sink.flush(events)
    } catch {
      /* fail-open: audit persistence never changes the authorization result */
    }
    return result
  }

  try {
    const requestedAt = clock.now()
    events.push(auditFrom("runtime_authorization_requested", input.request, "not_ready", requestedAt))

    // 1. Inert request identifiers.
    if (!requestFieldsValid(input.request)) {
      events.push(auditFrom("runtime_authorization_rejected", input.request, "invalid", requestedAt, ["invalid_runtime_authorization_input"]))
      return flushAndReturn(fail("invalid", "invalid_runtime_authorization_input"))
    }

    // 2. Early RBAC + kill-switch fast-fail (defense in depth).
    if (!hasExecutePermission(input.session)) {
      events.push(auditFrom("runtime_authorization_rejected", input.request, "forbidden", requestedAt, ["runtime_authorization_rbac_denied"]))
      return flushAndReturn(fail("forbidden", "runtime_authorization_rbac_denied"))
    }
    if (!areExternalActionsEnabled(env)) {
      events.push(auditFrom("runtime_authorization_blocked", input.request, "blocked", requestedAt, ["runtime_authorization_kill_switch_off"]))
      return flushAndReturn(fail("blocked", "runtime_authorization_kill_switch_off"))
    }

    // 3. THE ONLY await before the claim: resolve + snapshot the evidence bundle.
    const bundleSnap = await resolveBundleSnapshot(input.evidenceResolver, input.request)
    if (bundleSnap === null) {
      events.push(auditFrom("runtime_authorization_rejected", input.request, "not_ready", requestedAt, ["runtime_authorization_state_missing"]))
      return flushAndReturn(fail("not_ready", "runtime_authorization_state_missing"))
    }

    // 4. SYNCHRONOUS finalization — no `await` from here through claim initiation.
    const sessionSnap = snapshotSession(input.session)
    if (sessionSnap === null) {
      events.push(auditFrom("runtime_authorization_rejected", input.request, "forbidden", requestedAt, ["runtime_authorization_executor_invalid"]))
      return flushAndReturn(fail("forbidden", "runtime_authorization_executor_invalid"))
    }
    const claimAt = clock.now() // fresh, post-resolution
    const resolved = evaluateResolvedRuntimeAuthorization({ bundleSnap, sessionSnap, claimAt, request: input.request })
    if (!resolved.ok) {
      const kind = resolved.state === "blocked" ? "runtime_authorization_blocked" : "runtime_authorization_rejected"
      events.push(auditFrom(kind, input.request, resolved.state, claimAt, [resolved.issueCode]))
      return flushAndReturn(fail(resolved.state, resolved.issueCode))
    }
    const evidence = resolved.evidence
    // eligible is BUFFERED (not flushed): the sink must not run before the claim.
    events.push(auditFrom("runtime_authorization_eligible", evidence, "eligible", evidence.issued_at))

    // 5. FINAL RBAC + kill-switch recheck IN THIS CONSUMING FUNCTION, immediately
    //    before the claim. There must be NO await, callback, event emission, or
    //    logger call between these two checks and the claim initiation below.
    if (!hasExecutePermission(sessionSnap as unknown as Session)) {
      events.push(auditFrom("runtime_authorization_rejected", evidence, "forbidden", claimAt, ["runtime_authorization_rbac_denied"]))
      return flushAndReturn(fail("forbidden", "runtime_authorization_rbac_denied"))
    }
    if (!areExternalActionsEnabled(env)) {
      events.push(auditFrom("runtime_authorization_blocked", evidence, "blocked", claimAt, ["runtime_authorization_kill_switch_off"]))
      return flushAndReturn(fail("blocked", "runtime_authorization_kill_switch_off"))
    }
    // ── CLAIM-ADJACENT: no await/callback/emit between the check above and here ──
    const claimedPromise = input.approvalStore.claimApprovalForRuntime({
      tenantId: evidence.tenant_id as TenantId,
      workUnitId: evidence.workunit_id,
      actionPreviewId: evidence.action_preview_id,
      approvalId: evidence.approval_id,
      actionType: evidence.action_type as ApprovalActionType,
      targetHash: evidence.target_hash,
      payloadHash: evidence.payload_hash,
      claimedAt: evidence.issued_at,
    })
    const claimed = await claimedPromise

    if (!claimed) {
      // A false CAS buffers replayed and never claimed/created — no receipt.
      events.push(auditFrom("runtime_authorization_replayed", evidence, "used", evidence.issued_at, ["runtime_authorization_linkage_used"]))
      return flushAndReturn(fail("used", "runtime_authorization_linkage_used"))
    }
    events.push(auditFrom("runtime_authorization_claimed", evidence, "eligible", evidence.issued_at))

    // 6. Receipt construction — ONLY after the claim succeeds.
    const receipt = constructRuntimeAuthorizationReceipt(evidence)
    events.push(auditFrom("runtime_authorization_created", evidence, "authorized_not_executed", evidence.issued_at))
    return flushAndReturn(Object.freeze({ ok: true, state: "authorized_not_executed", receipt }))
  } catch {
    events.push(auditFrom("runtime_authorization_rejected", input.request, "invalid", clock.now(), ["runtime_authorization_validation_exception"]))
    return flushAndReturn(fail("invalid", "runtime_authorization_validation_exception"))
  }
}

// ─── Non-consuming dry-run evaluator ────────────────────────────

export type RuntimeAuthorizationDryRunResult =
  | { readonly disposition: "verified" }
  | { readonly disposition: "blocked" }
  | { readonly disposition: "not_ready" }
  | { readonly disposition: "forbidden" }

/**
 * The non-consuming dry-run decision: runs the EXACT same core as the real gate
 * (resolver, post-resolution timestamp, current executor, verifyApprovalLinkage,
 * Human Decision matrix, executor-vs-approver, execute RBAC, kill switch, exact
 * intended-action envelope) but NEVER claims Approval, NEVER consumes Linkage,
 * NEVER constructs a receipt, and NEVER calls a provider. A default-deny or
 * missing evidence resolver yields `not_ready` even when the Approval Record and
 * Preview binding are valid and the kill switch is enabled.
 */
export async function evaluateRuntimeAuthorizationDryRun(
  input: RuntimeAuthorizationCoreInput,
): Promise<RuntimeAuthorizationDryRunResult> {
  const env = input.env ?? process.env
  const clock = resolveClock(input.clock)
  try {
    // Early guards (parity with the consuming gate).
    if (!requestFieldsValid(input.request)) return { disposition: "not_ready" }
    if (!hasExecutePermission(input.session)) return { disposition: "forbidden" }
    if (!areExternalActionsEnabled(env)) return { disposition: "blocked" }

    // The only await; everything after is synchronous.
    const bundleSnap = await resolveBundleSnapshot(input.evidenceResolver, input.request)
    if (bundleSnap === null) return { disposition: "not_ready" }

    const sessionSnap = snapshotSession(input.session)
    if (sessionSnap === null) return { disposition: "forbidden" }
    const claimAt = clock.now()
    const resolved = evaluateResolvedRuntimeAuthorization({ bundleSnap, sessionSnap, claimAt, request: input.request })
    if (!resolved.ok) {
      if (resolved.state === "blocked") return { disposition: "blocked" }
      if (resolved.state === "forbidden") return { disposition: "forbidden" }
      return { disposition: "not_ready" }
    }

    // FINAL RBAC + kill-switch recheck (parity) — the dry-run NEVER claims.
    if (!hasExecutePermission(sessionSnap as unknown as Session)) return { disposition: "forbidden" }
    if (!areExternalActionsEnabled(env)) return { disposition: "blocked" }
    return { disposition: "verified" }
  } catch {
    return { disposition: "not_ready" }
  }
}
