/**
 * P6-FIX-012 (Issue #145): the server-side final Runtime Authorization gate.
 *
 * This is the ONLY place that turns a verified Approval Chain Linkage and a
 * runtime-eligible Human Decision into an `authorized_not_executed` receipt, and
 * only after an exact-binding atomic ApprovalStore claim wins.
 *
 * TEMPORAL FRESHNESS (P6-FIX-012 repair). The authoritative authorization
 * instant is generated by an injectable trusted clock AFTER the final
 * asynchronous evidence read — never before the resolver wait. That single fresh
 * timestamp drives executor-session validation, Linkage verification, Human
 * Decision eligibility, expiry derivation, and the final CAS, so a slow resolver
 * cannot let a stale timestamp survive across the async boundary. The client
 * never supplies the time.
 *
 * Ordering: early route guards → async evidence resolution → snapshot the bundle
 * once → fresh final timestamp → snapshot the session once → derive the current
 * executor → verify all evidence at the fresh timestamp → final RBAC recheck →
 * final kill-switch recheck → immediate exact-binding CAS with the same fresh
 * timestamp → construct receipt. The consuming path and the non-consuming
 * dry-run path share this exact core so they classify identical evidence the
 * same way before any claim.
 *
 * It never calls a provider, never creates an ExecutionResult, never returns an
 * externalRef, and never promotes a WorkUnit. It imports the single server-
 * private receipt constructor and no provider client.
 */

import type { Session } from "./session.ts"
import type { ApprovalStore } from "./approvalStore.ts"
import type { ApprovalActionType } from "../domain/types.ts"
import type { TenantId } from "../tenant/types.ts"
import { hasPermission } from "./rbac.ts"
import { areExternalActionsEnabled } from "./externalActions.ts"
import { createCanonicalSessionIdentity } from "../phase6/canonicalIdentity/index.ts"
import {
  evaluateRuntimeAuthorizationEligibility,
  projectRuntimeAuthorizationAudit,
  noopRuntimeAuthorizationAuditSink,
  snapshotDeepFrozen,
  type RuntimeAuthorizationAuditSink,
  type RuntimeAuthorizationEligibleEvidence,
  type RuntimeAuthorizationResult,
  type RuntimeAuthorizationEligibilityState,
} from "../phase6/runtimeAuthorization/index.ts"
import { constructRuntimeAuthorizationReceipt } from "./runtimeAuthorizationReceipt.ts"
import type {
  RuntimeAuthorizationEvidenceResolver,
  RuntimeAuthorizationEvidenceBundle,
} from "./runtimeAuthorizationEvidenceResolver.ts"

const EXECUTE_PERMISSION = "workunit.execute_external_action" as const

/** Injectable trusted clock. The client never supplies the time. */
export type RuntimeAuthorizationClock = {
  now(): string
}

/** Production clock: the server wall clock as a pinned UTC ISO string. */
export const systemRuntimeAuthorizationClock: RuntimeAuthorizationClock = {
  now() {
    return new Date().toISOString()
  },
}

// Test-only clock seam so route-level tests (which cannot inject a clock into
// the route) can pin the post-resolution evaluation instant to fixture times.
// Never set in production; an explicit per-call clock always takes precedence.
let testClockOverride: RuntimeAuthorizationClock | null = null

export function setRuntimeAuthorizationClockForTests(clock: RuntimeAuthorizationClock | null): void {
  testClockOverride = clock
}

export function resetRuntimeAuthorizationClockForTests(): void {
  testClockOverride = null
}

function resolveClock(explicit?: RuntimeAuthorizationClock): RuntimeAuthorizationClock {
  return explicit ?? testClockOverride ?? systemRuntimeAuthorizationClock
}

export type AuthorizeRuntimeCommandInput = {
  readonly session: Session
  readonly request: {
    readonly tenantId: string
    readonly workUnitId: string
    readonly actionPreviewId: string
    readonly approvalId: string
    readonly actionType: string
  }
  readonly approvalStore: ApprovalStore
  readonly evidenceResolver: RuntimeAuthorizationEvidenceResolver
  readonly env?: NodeJS.ProcessEnv
  readonly clock?: RuntimeAuthorizationClock
  readonly auditSink?: RuntimeAuthorizationAuditSink
}

type EligState = Exclude<RuntimeAuthorizationEligibilityState, "eligible">

function fail(state: EligState, issueCode: string): RuntimeAuthorizationResult {
  return Object.freeze({ ok: false, state, issue_code: issueCode })
}

/** Never let a malformed session throw during the RBAC check. */
function hasExecutePermission(session: Session): boolean {
  try {
    return hasPermission(session, EXECUTE_PERMISSION)
  } catch {
    return false
  }
}

function isNonEmptyString(value: unknown): value is string {
  return typeof value === "string" && value.length > 0
}

/**
 * Single-read snapshot of the current session. After evidence resolution the
 * session is snapshotted ONCE; canonical executor construction, session expiry,
 * final tenant identity, and final RBAC all read this one snapshot, never a
 * later read of the original session object.
 */
type SessionSnapshot = {
  readonly userId: unknown
  readonly tenantId: unknown
  readonly role: unknown
  readonly email: unknown
  readonly isDevSession: unknown
  readonly sessionId: unknown
  readonly createdAt: unknown
  readonly expiresAt: unknown
  readonly service_account?: unknown
  readonly on_behalf_of?: unknown
}

function snapshotSession(session: unknown): SessionSnapshot | null {
  if (typeof session !== "object" || session === null || Array.isArray(session)) return null
  const s = session as Record<string, unknown>
  const snap: Record<string, unknown> = {}
  for (const key of Object.keys(s)) snap[key] = s[key]
  return snap as unknown as SessionSnapshot
}

/**
 * Build the linkage verification context from the RAW server-owned sources,
 * stamping the fresh authorization instant into both `evaluated_at` and the
 * nested Identity Independence input's `evaluated_at` (one evaluation instant).
 */
function buildVerificationContext(
  sources: RuntimeAuthorizationEvidenceBundle["sources"],
  now: string,
): Record<string, unknown> {
  const rawIdentity = sources.identity_input
  const identityInput =
    rawIdentity !== null && typeof rawIdentity === "object" && !Array.isArray(rawIdentity)
      ? { ...(rawIdentity as Record<string, unknown>), evaluated_at: now }
      : rawIdentity
  return {
    tenant_id: sources.tenant_id,
    human_decision: sources.human_decision,
    review_evidence: sources.review_evidence,
    identity_input: identityInput,
    action_preview: sources.action_preview,
    approval_record: sources.approval_record,
    evaluated_at: now,
    revoked_review_evidence_ids: sources.revoked_review_evidence_ids,
    consumed_review_evidence_ids: sources.consumed_review_evidence_ids,
    revoked_approval_ids: sources.revoked_approval_ids,
    consumed_approval_ids: sources.consumed_approval_ids,
    revoked_approval_linkage_ids: sources.revoked_approval_linkage_ids,
    consumed_approval_linkage_ids: sources.consumed_approval_linkage_ids,
  }
}

// ─── Shared core (consuming + dry-run parity) ───────────────────

type CoreOk = { readonly ok: true; readonly evidence: RuntimeAuthorizationEligibleEvidence }
type CoreErr = { readonly ok: false; readonly state: EligState; readonly issueCode: string }
type CoreResult = CoreOk | CoreErr

export type RuntimeAuthorizationCoreInput = {
  readonly session: Session
  readonly request: AuthorizeRuntimeCommandInput["request"]
  readonly evidenceResolver: RuntimeAuthorizationEvidenceResolver
  readonly env?: NodeJS.ProcessEnv
  readonly clock?: RuntimeAuthorizationClock
}

/**
 * The shared, NON-CONSUMING core: early guards → async resolution → fresh
 * timestamp → session snapshot → executor → verify at the fresh instant → final
 * RBAC + kill-switch recheck. Returns eligible evidence WITHOUT claiming. Both
 * the consuming gate and the dry-run evaluator call this so they agree exactly
 * on the pre-claim classification.
 */
async function evaluateRuntimeAuthorizationCore(input: RuntimeAuthorizationCoreInput): Promise<CoreResult> {
  const { session, request, evidenceResolver } = input
  const env = input.env ?? process.env
  const clock = resolveClock(input.clock)

  // 1. Inert request identifiers must be present and well-formed.
  if (
    !isNonEmptyString(request.tenantId) ||
    !isNonEmptyString(request.workUnitId) ||
    !isNonEmptyString(request.actionPreviewId) ||
    !isNonEmptyString(request.approvalId) ||
    !isNonEmptyString(request.actionType)
  ) {
    return { ok: false, state: "invalid", issueCode: "invalid_runtime_authorization_input" }
  }

  // 2. Early RBAC + kill-switch fast-fail (defense in depth; rechecked below).
  if (!hasExecutePermission(session)) {
    return { ok: false, state: "forbidden", issueCode: "runtime_authorization_rbac_denied" }
  }
  if (!areExternalActionsEnabled(env)) {
    return { ok: false, state: "blocked", issueCode: "runtime_authorization_kill_switch_off" }
  }

  // 3. Server-authoritative evidence — never from the client. This is the last
  //    asynchronous read; everything after uses the post-resolution timestamp.
  const bundle = await evidenceResolver.resolveEvidenceBundle({
    tenantId: request.tenantId,
    workUnitId: request.workUnitId,
    actionPreviewId: request.actionPreviewId,
    approvalId: request.approvalId,
  })
  if (bundle === null) {
    return { ok: false, state: "not_ready", issueCode: "runtime_authorization_state_missing" }
  }

  // 4. Snapshot the resolver bundle ONCE; never read the resolver-owned object
  //    again. Every nested source is captured here.
  const bundleSnap = snapshotDeepFrozen(bundle) as RuntimeAuthorizationEvidenceBundle | null
  if (bundleSnap === null || typeof bundleSnap !== "object") {
    return { ok: false, state: "not_ready", issueCode: "runtime_authorization_state_missing" }
  }
  const envelope = bundleSnap.intendedAction
  if (
    !isNonEmptyString(envelope?.tenantId) || envelope.tenantId !== request.tenantId ||
    !isNonEmptyString(envelope.workUnitId) || envelope.workUnitId !== request.workUnitId ||
    !isNonEmptyString(envelope.actionPreviewId) || envelope.actionPreviewId !== request.actionPreviewId ||
    !isNonEmptyString(envelope.approvalId) || envelope.approvalId !== request.approvalId ||
    !isNonEmptyString(envelope.actionType) || envelope.actionType !== request.actionType ||
    !isNonEmptyString(envelope.targetHash) ||
    !isNonEmptyString(envelope.payloadHash)
  ) {
    return { ok: false, state: "stale", issueCode: "runtime_authorization_state_missing" }
  }

  // 5. FRESH authoritative authorization instant — AFTER the async read.
  const now = clock.now()

  // 6. Snapshot the current session ONCE and derive the executor at `now`.
  const sessionSnap = snapshotSession(session)
  if (sessionSnap === null) {
    return { ok: false, state: "forbidden", issueCode: "runtime_authorization_executor_invalid" }
  }
  const executorResult = createCanonicalSessionIdentity(sessionSnap, {
    actor_kind: "executor",
    expected_tenant_id: request.tenantId,
    observed_at: now,
  })
  if (!executorResult.ok) {
    return { ok: false, state: "forbidden", issueCode: "runtime_authorization_executor_invalid" }
  }
  const executor = executorResult.identity
  const sessionExpiresAt = sessionSnap.expiresAt

  // 7. Verify all evidence at the fresh instant (Linkage + HD matrix + executor
  //    separation + bounded expiry). Context is built from RAW sources with the
  //    fresh timestamp stamped in.
  const context = buildVerificationContext(bundleSnap.sources, now)
  const eligibility = evaluateRuntimeAuthorizationEligibility({
    linkage: bundleSnap.linkage,
    linkage_context: context,
    executor_identity: executor,
    intended_action: {
      tenant_id: envelope.tenantId,
      workunit_id: envelope.workUnitId,
      action_preview_id: envelope.actionPreviewId,
      approval_id: envelope.approvalId,
      action_type: envelope.actionType,
      target_hash: envelope.targetHash,
      payload_hash: envelope.payloadHash,
    },
    session_expires_at: typeof sessionExpiresAt === "string" ? sessionExpiresAt : "",
    issued_at: now,
  })
  if (!eligibility.ok) {
    return { ok: false, state: eligibility.state, issueCode: eligibility.issue_codes[0] ?? "runtime_authorization_state_missing" }
  }

  // 8. FINAL RBAC + kill-switch recheck, immediately before any claim. Never
  //    reuse the earlier `true`; re-evaluate from source (session snapshot).
  if (!hasExecutePermission(sessionSnap as unknown as Session)) {
    return { ok: false, state: "forbidden", issueCode: "runtime_authorization_rbac_denied" }
  }
  if (!areExternalActionsEnabled(env)) {
    return { ok: false, state: "blocked", issueCode: "runtime_authorization_kill_switch_off" }
  }

  return { ok: true, evidence: eligibility.evidence }
}

function auditFrom(
  kind: Parameters<typeof projectRuntimeAuthorizationAudit>[0]["event_kind"],
  evidenceOrRequest: RuntimeAuthorizationEligibleEvidence | AuthorizeRuntimeCommandInput["request"],
  state: RuntimeAuthorizationEligibilityState | "authorized_not_executed",
  now: string,
  issueCodes: readonly string[] = [],
) {
  const src = evidenceOrRequest as Record<string, unknown>
  return projectRuntimeAuthorizationAudit({
    event_kind: kind,
    tenant_id: src.tenant_id ?? src.tenantId,
    workunit_id: src.workunit_id ?? src.workUnitId,
    action_preview_id: src.action_preview_id ?? src.actionPreviewId,
    approval_id: src.approval_id ?? src.approvalId,
    action_type: src.action_type ?? src.actionType,
    state,
    issue_codes: issueCodes,
    evaluated_at: now,
  })
}

// ─── Consuming gate ─────────────────────────────────────────────

/**
 * The final runtime authorization gate. Returns a frozen discriminated result
 * with a stable internal issue code. On success the receipt is
 * `authorized_not_executed`; no provider is called and no state beyond the
 * one-time-use Approval claim is mutated. The full audit lifecycle
 * (requested → eligible → claimed → created, or rejected/replayed/blocked) is
 * emitted to the supplied sink.
 */
export async function authorizeRuntimeCommand(
  input: AuthorizeRuntimeCommandInput,
): Promise<RuntimeAuthorizationResult> {
  const clock = resolveClock(input.clock)
  const sink = input.auditSink ?? noopRuntimeAuthorizationAuditSink
  const emit = (e: ReturnType<typeof projectRuntimeAuthorizationAudit>) => {
    try {
      sink.emit(e)
    } catch {
      /* audit must never break the gate */
    }
  }
  try {
    const requestedAt = clock.now()
    emit(auditFrom("runtime_authorization_requested", input.request, "not_ready", requestedAt))

    const core = await evaluateRuntimeAuthorizationCore({
      session: input.session,
      request: input.request,
      evidenceResolver: input.evidenceResolver,
      env: input.env,
      clock,
    })
    if (!core.ok) {
      const kind = core.state === "blocked" ? "runtime_authorization_blocked" : "runtime_authorization_rejected"
      emit(auditFrom(kind, input.request, core.state, requestedAt, [core.issueCode]))
      return fail(core.state, core.issueCode)
    }

    const evidence = core.evidence
    // eligible is emitted ONLY after internal Linkage + policy eligibility and
    // the final RBAC + kill-switch recheck have all succeeded.
    emit(auditFrom("runtime_authorization_eligible", evidence, "eligible", evidence.issued_at))

    // 9. Exact-binding atomic one-time-use claim, using the SAME fresh instant.
    //    Never the legacy unbound single-id claim method.
    const claimed = await input.approvalStore.claimApprovalForRuntime({
      tenantId: evidence.tenant_id as TenantId,
      workUnitId: evidence.workunit_id,
      actionPreviewId: evidence.action_preview_id,
      approvalId: evidence.approval_id,
      actionType: evidence.action_type as ApprovalActionType,
      targetHash: evidence.target_hash,
      payloadHash: evidence.payload_hash,
      claimedAt: evidence.issued_at,
    })
    if (!claimed) {
      // A false CAS emits replayed and never claimed/created — no receipt.
      emit(auditFrom("runtime_authorization_replayed", evidence, "used", evidence.issued_at, ["runtime_authorization_linkage_used"]))
      return fail("used", "runtime_authorization_linkage_used")
    }
    emit(auditFrom("runtime_authorization_claimed", evidence, "eligible", evidence.issued_at))

    // 10. Receipt construction — ONLY after the claim succeeds.
    const receipt = constructRuntimeAuthorizationReceipt(evidence)
    emit(auditFrom("runtime_authorization_created", evidence, "authorized_not_executed", evidence.issued_at))
    return Object.freeze({ ok: true, state: "authorized_not_executed", receipt })
  } catch {
    emit(auditFrom("runtime_authorization_rejected", input.request, "invalid", clock.now(), ["runtime_authorization_validation_exception"]))
    return fail("invalid", "runtime_authorization_validation_exception")
  }
}

// ─── Non-consuming dry-run evaluator ────────────────────────────

export type RuntimeAuthorizationDryRunResult =
  | { readonly disposition: "verified" }
  | { readonly disposition: "blocked" }
  | { readonly disposition: "not_ready" }
  | { readonly disposition: "forbidden" }

/**
 * The non-consuming dry-run decision: runs the EXACT same core as the real gate
 * (resolver, post-resolution timestamp, current executor, verifyApprovalLinkage,
 * Human Decision matrix, executor-vs-approver, execute RBAC, kill switch, exact
 * intended-action envelope) but NEVER claims Approval, NEVER consumes Linkage,
 * NEVER constructs a receipt, and NEVER calls a provider. A default-deny or
 * missing evidence resolver yields `not_ready` even when the Approval Record and
 * Preview binding are valid and the kill switch is enabled.
 */
export async function evaluateRuntimeAuthorizationDryRun(
  input: RuntimeAuthorizationCoreInput,
): Promise<RuntimeAuthorizationDryRunResult> {
  try {
    const core = await evaluateRuntimeAuthorizationCore(input)
    if (core.ok) return { disposition: "verified" }
    if (core.state === "blocked") return { disposition: "blocked" }
    if (core.state === "forbidden") return { disposition: "forbidden" }
    return { disposition: "not_ready" }
  } catch {
    return { disposition: "not_ready" }
  }
}
